# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_docker:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'build')"
    steps:
    - name: checkout code
      uses: actions/checkout@v3
    - name: login docker
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: build image
      run: docker build -t strix-server .
    - name: push image
      uses: docker/build-push-action@v2
      with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/strix-message:${{ github.sha }}
          
  deploy:
    needs: build_docker
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'build')"
    steps:
    - name: deploy
      uses: appleboy/ssh-action@v0.1.3
      with:
          host: ${{ secrets.SERVER_ADDRESS }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIV_KEY }}
          script: |
            # Pull image mà được push lên DockerHub bên trên
            docker pull ${{ secrets.DOCKER_USERNAME }}/strix-message:${{ github.sha }}

            # Dừng và gỡ bỏ container hiện tại (nếu có)
            docker stop strix-message
            docker rm strix-message 

            # Chạy container mới với image đã pull về bên trên
            docker run -d -p 7777:7777 --name strix-message ${{ secrets.DOCKER_USERNAME }}/strix-message:${{ github.sha }}
